#:schema node_modules/wrangler/config-schema.json
name = "zuozihan-sublink"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "b0c3811fddfc40d1871176038bb75150" }
]
